image: node:latest

variables:
  CI_ARTIFACT_NAME: ${CI_PROJECT_NAME}-dist.zip

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - test
    - build
    - production

test:
    type: test
    stage: test
    script:
        - echo "[TEST] Running tests"
        - npm run test

build:
    type: build
    stage: build
    cache:
        paths:
            - node_modules/
    script:
        - echo "[BUILD] Building the app"
        - npm install --quiet
        - npm run build-prod
    artifacts:
        paths:
            - dist/
    only:
        - master
    

production:
    type: deploy
    stage: production
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master