image: node:latest

variables:
  CI_ARTIFACT_NAME: ${CI_PROJECT_NAME}-dist.zip

before_script:
    - apt-get update -qy

stages:
    - build
    - test
    - deploy

build:
    type: build
    stage: build
    cache:
        paths:
            - node_modules/
    script:
        - echo "[BUILD] Building the app"
        - npm install --quiet
        - npm run build-prod
    artifacts:
        expire_in: 1 week
        paths:
            - dist/
#    only:
#        - master

test:
    type: test
    stage: test
    cahce:
        policy: pull
        paths:
            - node_modules/
    script:
        - echo "[TEST] Running tests"
        - npm run test-ci

deploy_prod:
    stage: deploy
    environment: production
    only:
        - master
    dependencies:
        - build
    cache:
        policy: pull
        paths:
            - node_modules/
    script:
        - echo "[DEPLOY] Deploying the app"
        - npm install firebase-tools
        - npm run deploy