image: node:latest

variables:
  CI_ARTIFACT_NAME: ${CI_PROJECT_NAME}-dist.zip
  CLI_VERSION: 9.0.3

before_script:
    - apt-get update -qy

stages:
    - test
    - build
    - deploy

test:
    type: test
    stage: test
    image: trion/ng-cli-karma:${CLI_VERSION}
    allow_failure: false
    script:
        - echo "[TEST] Running tests"
        - ng test --progress false --watch false

build:
    type: build
    stage: build
    cache:
        paths:
            - node_modules/
    script:
        - echo "[BUILD] Building the app"
        - npm install --quiet
        - npm run build-prod
    artifacts:
        expire_in: 1 week
        paths:
            - dist/
    only:
        - master

deploy_prod:
    stage: deploy
    environment: production
    only:
        - master
    dependencies:
        - build
    cache:
        policy: pull
    script:
        - echo "[DEPLOY] Deploying the app"
        - npm install firebase-tools
        - npm run deploy